# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'legoX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for legoX

  target 'legoXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'legoXUITests' do
    # Pods for testing
  end

end
